---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: node1, ip: 10.2.2.3 }
    - { name: node2, ip: 10.2.2.4 }
    - { name: client, ip: 10.2.2.5 }
