---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.ceph.com/keys/release.asc
    state: present

- name: Add specified repository into sources list using specified filename.
  apt_repository:
    repo: "deb https://download.ceph.com/debian-luminous/ {{ ansible_distribution_release }} main"
    state: present
    filename: ceph
  failed_when: ansible_distribution != 'Ubuntu'

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - ceph-deploy
    - ceph-common

- import_tasks: ssh_key.yml

- import_tasks: hosts.yml
